### PR TITLE
Ngap stopwatch

### PR DESCRIPTION
**Pull request by ndp-opendap**
In this PR I have:

I added timers to
```
EffectiveUrlCache::get_effective_url()                   // Resolution of CF URLs to S3 Urls
DmrppRequestHandler::dap_build_dap4data()                // Data Access - may subsume get_effective_url()
DmrppRequestHandler::dap_build_dap2data()                // Data Access - may subsume get_effective_url()
NgapApi::convert_ngap_resty_path_to_data_access_url()    // CMR query
NgapContainer::access()                                  // dmr++ retrieval fro s3  
```

The new timers activation is dependent on the existing timer trigger and on verbose logging:
```
BESStopWatch sw;
if (BESISDEBUG(TIMING_LOG) || BESLog::TheLog()->is_verbose()) 
    sw.start(prolog + "timer" , dhi.data[REQUEST_ID]);
```

I made changes to BESStopwatch so that output can go to either:
```
std::stringstream msg;
msg << "[" << BESDebug::GetPidStr() << "][" << _log_name << "]";
msg << "[" << _req_id << "][STOPPED][" << stoptime << " ms]";
msg << "[" << _timer_name << "][ELAPSED][" << elapsed << " ms]" << endl;
if (BESDebug::GetStrm())
    *(BESDebug::GetStrm()) << msg.str();
VERBOSE(msg.str() );
```

### CODE REVIEW

**Comment by ndp-opendap** [comment]
But how do I make it time the data retrieval??

**Comment by jgallagher59701** [comment]
This is good.

For the future, in BESLog.h there is a VERBOSE() macro that is the equivalent of the LOG() macro.

**Comment by ndp-opendap** [comment]
Hmmm I am using that macro throughout the changes that I made.

**Comment by jgallagher59701** [comment]
Yeah - the VERBOSE thing - I was reading fast and missed a detail about the code. No worries.

This looks good.

**Pull request merged**
