### PR TITLE
CoverageJSON Response Handler for OPeNDAP Project - BES

### PR DESCRIPTION
**Pull request by hemphilc**
This is the initial pull request for the CoverageJSON Response Handler for OPeNDAP project. This project was an Oregon State University 2018 capstone project sponsored by NASA JPL. This response handler module, fileout_covjson, was modeled after the existing fileout_json response handler.

This pull request was submitted in tandem with the covjson branch in the OLFS project.

OLFS Pull Request Reference https://github.com/OPENDAP/olfs/pull/35

### CODE REVIEW

**Comment by lewismc** [comment]
@hemphilc issue is flagged as follows

```
autom4te --language=autotest -I '.' -o fileout_covjsonTest.tmp fileout_covjsonTest.at
mv fileout_covjsonTest.tmp fileout_covjsonTest
/bin/bash './fileout_covjsonTest' 
## ----------------------------------------------------- ##
## bes 3.19.1 test suite: bes.conf besstandalone getdap. ##
## ----------------------------------------------------- ##
fileout_covjsonTest: error: cannot find besstandalone
make[4]: *** [check-local] Error 1
make[4]: Leaving directory `/home/travis/build/OPENDAP/bes/modules/fileout_covjson/tests'
make[3]: *** [check-am] Error 2
make[3]: Leaving directory `/home/travis/build/OPENDAP/bes/modules/fileout_covjson/tests'
make[2]: *** [check-recursive] Error 1
make[2]: Leaving directory `/home/travis/build/OPENDAP/bes/modules/fileout_covjson'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/home/travis/build/OPENDAP/bes/modules'
make: *** [check-recursive] Error 1
```

Specifically, ```fileout_covjsonTest: error: cannot find besstandalone```

**Comment by jgallagher59701** [comment]
I just looked at this and I think I see the problem. Try adding the following, edited to match the covjson code, to configure.ac near the end (look at line ~ 960):

AC_CONFIG_TESTDIR(modules/csv_handler/tests, [standalone])

This is the marco that sets the information for the autotest-based regression tests. Not sure why its working for you locally, but these CI builds are done on a fresh VM every time, so little fixes you put in place once and forgot about will stick around on your own machine but be absent on the machine used for a CI build.

**Comment by jgallagher59701** [comment]
Based on what I see, I suggest you comment out the failing test and see if the CI build will pass - I take it that these tests pass on your local machine? Also, have you run _make distcheck -j9_ to see if that passes locally?

**Comment by hemphilc** [comment]
Removed that failing test as it is not valid for this module, at least from my perspective.

**Comment by hemphilc** [comment]
All checks are now passing!! YES! Thank you very much for your help on this, Jim.

**Comment by jgallagher59701** [comment]
Once the copyright is sorted, we're good to go and I'll merge it. I think an awk script should handle the edits - or maybe eclipse can do it. Or sed. 

Thanks for the work you put into this!

**Comment by hemphilc** [comment]
@jgallagher59701 -- All deprecated info in the source headers have been removed!

**Comment by jgallagher59701** [comment]
Merged!

Thanks!

**Comment by lewismc** [comment]
Thanks @jgallagher59701 excellent work @hemphilc

**Pull request merged**
