### PR TITLE
Starting to add basic CI

### PR DESCRIPTION
**Pull request by captainkirk99**
Starting to add GitHub CI. Still a little work to do here. I will pick it up again tomorrow...

### CODE REVIEW

**Comment by captainkirk99** [comment]
@jgallagher59701 the make is failing like this. Do you know why?:

```
make[4]: Leaving directory '/home/runner/work/bes/bes/http/unit-tests'
656
make[3]: Leaving directory '/home/runner/work/bes/bes/http/unit-tests'
657
make[2]: Leaving directory '/home/runner/work/bes/bes/http'
658
Making all in dispatch
659
make[2]: Entering directory '/home/runner/work/bes/bes/dispatch'
660
Making all in .
661
make[3]: Entering directory '/home/runner/work/bes/bes/dispatch'
662
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -I../dap -I../xmlcommand  -I/usr/include/libxml2  -I/include  -g -O2 --pedantic --std=c++11 -MT BESInterface.lo -MD -MP -MF .deps/BESInterface.Tpo -c -o BESInterface.lo BESInterface.cc
663
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I../dap -I../xmlcommand -I/usr/include/libxml2 -I/include -g -O2 --pedantic --std=c++11 -MT BESInterface.lo -MD -MP -MF .deps/BESInterface.Tpo -c BESInterface.cc  -fPIC -DPIC -o .libs/BESInterface.o
664
In file included from BESInterface.cc:56:
665
../dap/BESDapError.h:42:10: fatal error: Error.h: No such file or directory
666
   42 | #include "Error.h"
667
      |          ^~~~~~~~~
668
compilation terminated.
669
make[3]: *** [Makefile:943: BESInterface.lo] Error 1
```

**Comment by jgallagher59701** [comment]
Ed, To build the BES, you need all the stuff in the repo hyrax-dependencies. That repo has a functioning Github Actions build workflow on the branch actions-test. I would like it if you would integrate the build of the hyrax-dependencies repo into this workflow and not get individual tar balls from various places. The hyrax-dependencies has a Makefile that is hand written and includes various targets for cases we need to support (OSX development machines, Ubuntu-based CI/CD machines and RPM packages for NASA - which are special RPM packages in ways that require a phone call).

Thanks,
James

**Comment by captainkirk99** [comment]
OK will do.

**Comment by jgallagher59701** [comment]
Closed since Emmanuel Babalola is working on this task.

**Pull request closed without merging**
