### PR TITLE
Refactor for BESKeys and TheBESKeys: Added a virtual dtor

### PR DESCRIPTION
**Pull request by jgallagher59701**
I also changed how BESKeys *TheBESKeys::TheKeys() was written so
that the static class variable TheBESKeys::ConfigFile is set
when a bes.conf file is found in one of the etc dirs.

And I changed how the code searches for the bes.conf file if no value is given - I changed the nested if code to code that uses multiple exit points. That's 'bad' but I was having a hard time sorting out how the other code worked... ;-)

### CODE REVIEW

**Comment by jgallagher59701** [comment]
Patrick,

We're shooting for a Monday release - any chance you can give this a once over soon? If not, just let me know and I'll either hold it back or punt and merge it. I hope to have CI working again later today; the problem is that libdap as cached by Travis is too old for this code.

Thanks,
James

**Comment by mrpatrickwest** [comment]
What about the Travis CI fail?

**Comment by jgallagher59701** [comment]
> On Oct 21, 2015, at 12:49 PM, Patrick West <notifications@github.com> wrote:
> 
> What about the Travis CI fail?
> 
> 
Fixed
> —
> Reply to this email directly or view it on GitHub <https://github.com/OPENDAP/bes/pull/11#issuecomment-149991000>.
> 

--
James Gallagher
jgallagher@opendap.org

**Comment by mrpatrickwest** [comment]
Still shows as failing. 

checking for bison 3.0... configure: error: not found

The command "bash ./install_bes_source_deps.sh" failed and exited with 1 during .

Your build has been stopped.

**Comment by ndp-opendap** [comment]
https://travis-ci.org/OPENDAP/bes

Shows as passed, I have no idea why Github hasn't updated.

**Comment by mrpatrickwest** [comment]
I'm good with it then. :shipit:

**Pull request merged**
