### PR TITLE
Libcurl lcd

### PR DESCRIPTION
**Pull request by ndp-opendap**
This PR is a second effort to consolidate the libcurl HTTP code for Hyrax. The first valiant was made by Slav and unfortunately things moved along while his work languished unmerged. I am using his branch to feed changes in to this one. One module at a time...

### CODE REVIEW

**Comment by jgallagher59701** [comment]
Merge!

**Comment by ndp-opendap** [comment]
> Merge!

A merge would be a little premature - I have only added the `http` dir and converted the `cmr_module` to use it. On the bright side the tests are all passing.

**Comment by jgallagher59701** [comment]
Party on!

**Comment by ndp-opendap** [comment]
Merge??

**Pull request merged**
