### PR TITLE
Cmdln test fixes

### PR DESCRIPTION
**Pull request by jgallagher59701**
Could this be a solution? Maybe - Im not 100% happy with these tests, but I think the baselines are now correct for the default data. I'm wondering about things like the server user_name parameter and line numbers.

### CODE REVIEW

**Comment by jgallagher59701** [comment]
Oh, and the travis build is modified to run these, hence the PR, but not the distcheck part of the build.

**Comment by jgallagher59701** [comment]
Maybe changes from hyrax-1.15 are needed for this branch to build:

Caught plugin exception during initialization of cmr module:
    BES.Catalog.CMR.RootDirectory not defined in BES configuration file
Could not initialize the modules to get the log contexts.
Developer Mode: Not setting group or user ids
Caught plugin exception during initialization of cmr module:
    BES.Catalog.CMR.RootDirectory not defined in BES configuration file
The beslistener status is not 'BESLISTENER_RUNNING' (it is '219028048')  the master pid was not changed.
besdaemon: server cannot mount at first try (core dump). Please correct problems on the process manager /home/travis/install/bin/beslistener
BES PID file exists but process not running, cleaning up
FAILED: The BES daemon did not appear to start

**Comment by ndp-opendap** [comment]
Yes. The whole point of hyrax-1.15 is to address these issues.

**Comment by jgallagher59701** [comment]
So, should we merge hyrax-1.15 to master? (PR, et c.)

**Comment by ndp-opendap** [comment]
Sure! The tests don't pass but who cares?

**Comment by ndp-opendap** [comment]
(No I think we need to fix the tests. and maybe talk)

**Pull request merged**
