### PR TITLE
trying github actions build

### PR DESCRIPTION
**Pull request by captainkirk99**
trying github actions build

### CODE REVIEW

**Comment by captainkirk99** [comment]
@jgallagher59701 this is a modified version of the STAREmaster CI file. It will build a few of the dependencies and then try an autoreconf -i. It does nothing further, because I want to get that passing so it caches the dependencies. But it's not even running.

I expected it to run when I made it part of this PR, but it does not. Perhaps I need to be added to the list of developers on this repo? Or perhaps you need to merge this to get the ball rolling?

On all my other repos, it started working as soon as I submitted the PR with the workflow. So propably this is because I am not a developer on this github repo...

**Comment by captainkirk99** [comment]
OK, now that I think about it, it makes sense that this would not work for people not on the team...

**Comment by jgallagher59701** [comment]
This is running into our issues with the deps that come from our other NASA work. I'm working on a fix.

**Comment by captainkirk99** [comment]
I think if you add me to the list of developers on the project I can get the GitHub actions working without worrying about the travis build.

But right now it does not even run my attempt on github actions, so we can't see how it is failing...

**Comment by captainkirk99** [comment]
Trying this again as #454

**Pull request closed without merging**
